// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_UMNWHsFQqYX8Qp5maCbCZAscfC_Mao',
    appId: '1:1049630213063:web:c2d9c6d8a5a7e59db08fe2',
    messagingSenderId: '1049630213063',
    projectId: 'yarayetanotherrunnerapp',
    authDomain: 'yarayetanotherrunnerapp.firebaseapp.com',
    storageBucket: 'yarayetanotherrunnerapp.firebasestorage.app',
    measurementId: 'G-KD3N640REC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3h869u0ujQGpPPmvOEwqAiiLRuoLCBE',
    appId: '1:1049630213063:android:dca6ad458e595ba5b08fe2',
    messagingSenderId: '1049630213063',
    projectId: 'yarayetanotherrunnerapp',
    storageBucket: 'yarayetanotherrunnerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzn1ypZEvz378IKX_zPrTN8XosqiEivU',
    appId: '1:1049630213063:ios:6d53d85120ea72d3b08fe2',
    messagingSenderId: '1049630213063',
    projectId: 'yarayetanotherrunnerapp',
    storageBucket: 'yarayetanotherrunnerapp.firebasestorage.app',
    androidClientId: '1049630213063-r2q25gr2t463iia308t06jt1ruoajtho.apps.googleusercontent.com',
    iosClientId: '1049630213063-vpoqe0guu4rsc9pd7r5tkmlgtkoac5u7.apps.googleusercontent.com',
    iosBundleId: 'com.matheussilvagarcia.anotherrunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzn1ypZEvz378IKX_zPrTN8XosqiEivU',
    appId: '1:1049630213063:ios:6d53d85120ea72d3b08fe2',
    messagingSenderId: '1049630213063',
    projectId: 'yarayetanotherrunnerapp',
    storageBucket: 'yarayetanotherrunnerapp.firebasestorage.app',
    androidClientId: '1049630213063-r2q25gr2t463iia308t06jt1ruoajtho.apps.googleusercontent.com',
    iosClientId: '1049630213063-vpoqe0guu4rsc9pd7r5tkmlgtkoac5u7.apps.googleusercontent.com',
    iosBundleId: 'com.matheussilvagarcia.anotherrunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM_UMNWHsFQqYX8Qp5maCbCZAscfC_Mao',
    appId: '1:1049630213063:web:1e2a39fecd14f031b08fe2',
    messagingSenderId: '1049630213063',
    projectId: 'yarayetanotherrunnerapp',
    authDomain: 'yarayetanotherrunnerapp.firebaseapp.com',
    storageBucket: 'yarayetanotherrunnerapp.firebasestorage.app',
    measurementId: 'G-WLYLHPN06F',
  );

}